---

- name:             install imagemagick packages
  apt:              name={{ item }} state=present install_recommends=no
  with_items:
    - imagemagick
    - libmagickwand-dev
    - ghostscript
    - netpbm
