---

- name:             install some tools
  apt:              name={{ item }} state=present
  with_items:
    - ack-grep
    - byobu
    - curl
    - git
    - grc
    - htop
    - tree
    - vim

- name:             install some more tools
  apt:              name={{ item }} state=present
  with_items:
    - mc
    - tig

- name:             install development and sysadmin tools
  apt:              name={{ item }} state=present
  with_items:
    - build-essential
    - debian-goodies

- name:             install some -dev packages
  apt:              name={{ item }} state=present
  with_items:
    - zlib1g-dev
    - libssl-dev
    - libreadline-gplv2-dev
    - libxml2-dev
    - libxslt1-dev

- name:             remove unwanted packages
  apt:              name={{ item }} state=absent
  with_items:
    - rpcbind
    - cloud-init

- name:             set default editor
  command:          update-alternatives --set editor {{ alt.editor }}
  register:         alt_editor
  changed_when:     '"using" in alt_editor.stdout'

- name:             link ack to ack-grep
  file:             path=/usr/local/bin/ack src=/usr/bin/ack-grep state=link

- name:             create directories in /opt + /root/cache
  file:             path={{ item }} state=directory mode=755
  with_items:
    - /opt/src
    - /opt/pkg
    - /root/cache
