---

- name:             install libav packages
  apt:              name={{ item }} state=present
  with_items:
    - libav-tools
    - libavcodec-extra-53
    - libavdevice-extra-53
    - libavfilter-extra-2
    - libavformat-extra-53
    - libpostproc-extra-52
