---

- name:             install nginx packages
  apt:              name=nginx-full state=present

- name:             disable default nginx site
  file:             path=/etc/nginx/sites-enabled/default state=absent
  notify:           restart nginx
