---

- name:             configure VM
  hosts:            all
  sudo:             true

  vars:
    alt:
      editor:       /usr/bin/vim.basic
    git:
      user:         vagrant
      email:        vagrant@localhost
    gh_repos:
      - obfusk/dev-misc
      - obfusk/map.sh
      - obfusk/sh-config
      - obfusk/taskmaster
      - obfusk/venv
      - kchmck/vim-coffee-script
      - plasticboy/vim-markdown
    links:
      root:
        - path:       /usr/local/bin/filter
          src:        /opt/src/map.sh/bin/filter
        - path:       /usr/local/bin/map
          src:        /opt/src/map.sh/bin/map
        - path:       /usr/local/bin/taskmaster
          src:        /opt/src/taskmaster/taskmaster
        - path:       /usr/local/bin/venv
          src:        /opt/src/venv/venv
      vagrant:
        - path:       ~/.vimrc
          src:        /opt/src/dev-misc/vimrc
    gems:
      - bundler
      - pry
    npms: [] # TODO
    # - coffee-script

  roles:
    - vagrant
  # - update
  # - etckeeper
    - common
  # - repos
  # - links
    - ruby
  # - python
  # - sqlite
  # - memcached
  # - redis
  # - imagemagick
  # - nginx
  # - gitolite
  # - phantomjs
  # - libav
  # - X
  # - vnc
  # - pg
  # - pg-pgdg
  # - mongo
  # - mongo-10gen
  # - nodejs      TODO
  # - nodejs-tar  TODO
    - { role: vagrant-user, sudo_user: vagrant }
