---

- name:             configure VM
  hosts:            all
  sudo:             true
  sudo_user:        root

  vars:
    release:        precise
    alt:
      editor:       /usr/bin/vim.basic
    git:
      user:         vagrant
      email:        vagrant@localhost
    gh_repos:
      - obfusk/dev-misc
      - obfusk/map.sh
      - obfusk/sh-config
      - obfusk/taskmaster
      - obfusk/venv
      - kchmck/vim-coffee-script
      - plasticboy/vim-markdown
    ruby_version:   1.9.1
    links:
      root:
        - path:     /usr/local/bin/filter
          src:      /opt/src/map.sh/bin/filter
        - path:     /usr/local/bin/map
          src:      /opt/src/map.sh/bin/map
        - path:     /usr/local/bin/taskmaster
          src:      /opt/src/taskmaster/taskmaster
        - path:     /usr/local/bin/venv
          src:      /opt/src/venv/venv
      vagrant:
        - path:     ~/.vimrc
          src:      /opt/src/dev-misc/vimrc
    gems:
      - bundler
      - pry
      - localconfig
    npms: []
    # - coffee-script
    # - uglify-js

  roles:
    - vagrant
    - update
    - etckeeper
    - common
    - repos
    - links
    - ruby-1.9
  # - ruby-2.0  # trusty
    - python
    - sqlite
    - memcached
    - redis
    - imagemagick
    - nginx
    - gitolite
    - phantomjs
    - libav-precise
  # - libav-trusty
    - X
    - vnc
    - pg-9.1    # precise
  # - pg-9.3    # trusty
  # - pg-pgdg
    - mongo
  # - mongo-10gen
    - nodejs
  # - nodejs-tar
    - { role: vagrant-user, sudo_user: vagrant }
