---

- name:             configure VM
  hosts:            all
  user:             root

  vars:
    editor:         /usr/bin/vim.basic
    git:
      user:         vagrant
      email:        vagrant@localhost

  tasks:
    - name:         lock password
      command:      passwd -l vagrant

  roles:
    - update
    - common
    - ruby
    - python
    - sqlite
    - memcached
    - redis
    - imagemagick
    - nginx
    - gitolite
    - phantomjs
    - libav
    - X
    - vnc
  # - pg
    - pg-pgdg
  # - mongo
    - mongo-10gen
  # - nodejs
    - nodejs-tar
