---

# to use precise instead of trusty:
#
#   * s/trusty/precise/ in Vagrantfile, build.sh,
#     provision.sh (only $RELEASE!)
#   * release: s/trusty/precise/
#   * ruby_version: s/2.0.0/1.9.1/
#   * gem_exec: s/2.0$//
#   * disable the 2.0 symlinks for vagrant
#   * swap the comments in front of the roles marked trusty/precise

- name:             configure VM
  hosts:            all
  sudo:             true
  sudo_user:        root

  vars:
    release:        trusty
  # release:        precise
    alt:
      editor:       /usr/bin/vim.basic
    git:
      user:         vagrant
      email:        vagrant@localhost
    gh_repos:
      - obfusk/dev-misc
      - obfusk/map.sh
      - obfusk/sh-config
      - obfusk/taskmaster
      - obfusk/venv
      - kchmck/vim-coffee-script
      - plasticboy/vim-markdown
    ruby_version:   2.0.0   # trusty
  # ruby_version:   1.9.1   # precise
    gem_exec:       /usr/bin/gem2.0
  # gem_exec:       /usr/bin/gem
    links:
      root:
        - path:     /usr/local/bin/filter
          src:      /opt/src/map.sh/bin/filter
        - path:     /usr/local/bin/map
          src:      /opt/src/map.sh/bin/map
        - path:     /usr/local/bin/taskmaster
          src:      /opt/src/taskmaster/taskmaster
        - path:     /usr/local/bin/venv
          src:      /opt/src/venv/venv
      vagrant:
        - path:     ~/.vimrc
          src:      /opt/src/dev-misc/vimrc
        # trusty {
        - path:     ~/bin/erb
          src:      /usr/bin/erb2.0
        - path:     ~/bin/gem
          src:      /usr/bin/gem2.0
        - path:     ~/bin/irb
          src:      /usr/bin/irb2.0
        - path:     ~/bin/rdoc
          src:      /usr/bin/rdoc2.0
        - path:     ~/bin/ri
          src:      /usr/bin/ri2.0
        - path:     ~/bin/ruby
          src:      /usr/bin/ruby2.0
        - path:     ~/bin/testrb
          src:      /usr/bin/testrb2.0
        # } trusty
    gems:
      - bundler
      - pry
      - localconfig
    npms: []      # these won't work w/ default npm in precise
    # - coffee-script
    # - uglify-js

  roles:
    - vagrant
    - update
    - etckeeper
    - common
    - repos
    - links
    - ruby-2.0    # trusty
  # - ruby-1.9    # precise
    - python
    - sqlite
    - memcached
    - redis
    - imagemagick
    - nginx
    - gitolite
    - phantomjs
    - libav-trusty
  # - libav-precise
    - X
    - vnc
    - pg-9.3      # trusty
  # - pg-9.1      # precise
  # - pg-pgdg     # for precise w/ newer pg
    - mongo
  # - mongo-10gen # for precise w/ newer mongo
    - nodejs-trusty
  # - nodejs-precise
  # - nodejs-tar  # for precise w/ newer nodejs
    - { role: vagrant-user, sudo_user: vagrant }
